apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bb5myr68t-nodejs
  janus-idp.io/tekton: bb5myr68t-nodejs
  backstage.io/kubernetes-id: bb5myr68t-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: bb5myr68t-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
